name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build

    - name: Deploy to server
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 206.81.1.88
        username: root
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          echo "🚀 Starting deployment..."
          cd /var/www/bound-ai-dashboard || exit 1
          git status
          git pull origin main
          echo "📦 Installing dependencies..."
          npm ci
          echo "🔨 Building application..."
          npm run build
          echo "🔄 Restarting application..."
          pm2 reload bound-ai || pm2 restart bound-ai || (pm2 stop bound-ai; pm2 start npm --name "bound-ai" -- start)
          pm2 status
          echo "✅ Deployment completed successfully!"